### ISSUE TITLE
Did you log the response from aws-sdk?

### ISSUE THREAD

**Issue by JordiSapesPlanas** [Pablito2020/aws-playground#1]
https://github.com/Pablito2020/aws-playground/blob/5a062544b716b49582f8fc6472f43ac139c4ef25/practices/practice2/get.ts#L17

Hola Pablo, estas retornant tota la resposta de la [AWS-SDK ](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#get-property). És aixó el que realment vols? O nomes vols retornar el item de la resposta?

**Comment by Pablito2020** [comment]
Sí, vaig veure que retornava el tipus GetItemOutput i no Item, però com literalment es mostrava el mateix, però amb un objecte dintre d'un objecte és a dir:
```
{
  {
   "id": 1
   "data": ...
  }
}
```
Vaig pensar que ja era suficient. Però si que es veritat que com a bona pràctica, s'hauria de retornar sol les dades que es demanen. Per tant ho he solucionat al commit referenciat a dalt.
